jet/jet_dashboard/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog

    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.jet_dashboard import dashboard
from jet.jet_dashboard.views import update_dashboard_modules_view, add_user_dashboard_module_view, \
    update_dashboard_module_collapse_view, remove_dashboard_module_view, UpdateDashboardModuleView, \
    load_dashboard_module_view, reset_dashboard_view, propagate_jet_dashboard, clear_cache, generate_custom_dashboard, \
    download_my_dashboard
from jet.jet_dashboard.dashboard_modules.google_analytics_views import google_analytics_callback_view, \
    google_analytics_grant_view, google_analytics_revoke_view

app_name = 'jet_dashboard'

urlpatterns = [
    url(
        r'^module/(?P<pk>\d+)/$',
        UpdateDashboardModuleView.as_view(),
        name='update_module'
    ),
    url(
        r'^update_dashboard_modules/$',
        update_dashboard_modules_view,
        name='update_dashboard_modules'
    ),
    url(
        r'^add_user_dashboard_module/$',
        add_user_dashboard_module_view,
        name='add_user_dashboard_module'
    ),
    url(
        r'^update_dashboard_module_collapse/$',
        update_dashboard_module_collapse_view,
        name='update_dashboard_module_collapse'
    ),
    url(
        r'^remove_dashboard_module/$',
        remove_dashboard_module_view,
        name='remove_dashboard_module'
    ),
    url(
        r'^load_dashboard_module/(?P<pk>\d+)/$',
        load_dashboard_module_view,
        name='load_dashboard_module'
    ),
    url(
        r'^reset_dashboard/$',
        reset_dashboard_view,
        name='reset_dashboard'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'jet'},
        name='jsi18n'
    ),
    url(r'^propagate_jet_dashboard/',
        propagate_jet_dashboard,
        name='propagate_jet_dashboard'),
    url(r'^clear_cache/',
        clear_cache,
        name='clear_cache'),
    url(r'^generate_custom_dashboard/',
        generate_custom_dashboard,
        name='generate_custom_dashboard'),
    url(r'^download_my_dashboard/',
        download_my_dashboard,
        name='download_my_dashboard'),
    url(r'^google-analytics/grant/(?P<pk>\d+)/$', google_analytics_grant_view, name='google-analytics-grant'),
    url(r'^google-analytics/revoke/(?P<pk>\d+)/$', google_analytics_revoke_view, name='google-analytics-revoke'),
    url(r'^google-analytics/callback/', google_analytics_callback_view, name='google-analytics-callback'),
]

urlpatterns += dashboard.urls.get_urls()

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns

    urlpatterns = patterns('', *urlpatterns)

jet/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

jet/jet_dashboard/models.py
from importlib import import_module
import json
from django.db import models
try:
    from django.utils.encoding import python_2_unicode_compatible
except ImportError:
    from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from jet.utils import LazyDateTimeEncoder


@python_2_unicode_compatible
class UserDashboardModule(models.Model):
    title = models.CharField(verbose_name=_('Title'), max_length=255)
    title_ar = models.CharField(verbose_name=_('Title AR'), max_length=255, null=True, blank=True)  # Remove this if no need for Arabic
    module = models.CharField(verbose_name=_('module'), max_length=255)
    app_label = models.CharField(verbose_name=_('application name'), max_length=255, null=True, blank=True)
    user = models.PositiveIntegerField(verbose_name=_('user'))
    column = models.PositiveIntegerField(verbose_name=_('column'))
    order = models.IntegerField(verbose_name=_('order'))
    settings = models.TextField(verbose_name=_('settings'), default='', blank=True)
    children = models.TextField(verbose_name=_('children'), default='', blank=True)
    collapsed = models.BooleanField(verbose_name=_('collapsed'), default=False)

    class Meta:
        verbose_name = _('user jet_dashboard module')
        verbose_name_plural = _('user jet_dashboard modules')
        ordering = ('column', 'order')

    def __str__(self):
        return self.module

    def load_module(self):
        try:
            package, module_name = self.module.rsplit('.', 1)
            package = import_module(package)
            module = getattr(package, module_name)
            return module
        except AttributeError:
            return None
        except ImportError:
            return None

    def pop_settings(self, pop_settings):
        settings = json.loads(self.settings)

        for setting in pop_settings:
            if setting in settings:
                settings.pop(setting)

        self.settings = json.dumps(settings, cls=LazyDateTimeEncoder)
        self.save()

    def update_settings(self, update_settings):
        settings = json.loads(self.settings)

        settings.update(update_settings)

        self.settings = json.dumps(settings, cls=LazyDateTimeEncoder)
        self.save()

jet/models.py
from django.db import models
from django.utils import timezone
try:
    from django.utils.encoding import python_2_unicode_compatible
except ImportError:
    from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _, activate
from django.apps import apps
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

from adminsortable.models import Sortable
from solo.models import SingletonModel


User = get_user_model()


@python_2_unicode_compatible
class Bookmark(models.Model):
    url = models.URLField(verbose_name=_('URL'))
    title = models.CharField(verbose_name=_('title'), max_length=255)
    user = models.PositiveIntegerField(verbose_name=_('user'))
    date_add = models.DateTimeField(verbose_name=_('date created'), default=timezone.now)

    class Meta:
        verbose_name = _('bookmark')
        verbose_name_plural = _('bookmarks')
        ordering = ('date_add',)

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class PinnedApplication(models.Model):
    app_label = models.CharField(verbose_name=_('application name'), max_length=255)
    user = models.PositiveIntegerField(verbose_name=_('user'))
    date_add = models.DateTimeField(verbose_name=_('date created'), default=timezone.now)

    class Meta:
        verbose_name = _('pinned application')
        verbose_name_plural = _('pinned applications')
        ordering = ('date_add',)

    def __str__(self):
        return self.app_label


@python_2_unicode_compatible
class PermissionAppHelp(models.Model):
    # activate('en')
    # APP = [(app.verbose_name, app.verbose_name) for app in apps.get_app_configs() if app.label not in ['sessions', 'contenttypes', 'admin']]

    app = models.CharField(max_length=100, unique=True)
    help_text = models.TextField(verbose_name=_("Help Text"), null=True, blank=True)
    show_in_permission = models.BooleanField(default=True, verbose_name=_("Show in Permission Page"))

    def __str__(self):
        return self.app


# def get_model():
#     activate('en')
#     MODEL = []
#     for app in apps.get_app_configs():
#         try:
#             for model in app.get_models():
#                 model_name = str(app.verbose_name) + " / " + str(model._meta.verbose_name)
#                 MODEL.append((model_name, model_name))
#         except:
#             pass
#     return MODEL


@python_2_unicode_compatible
class PermissionModelHelp(models.Model):
    app_model = models.CharField(max_length=150, unique=True)
    help_text = models.TextField(verbose_name=_("Help Text"), null=True, blank=True)
    show_in_permission = models.BooleanField(default=True, verbose_name=_("Show in Permission Page"))

    def __str__(self):
        return self.app_model


@python_2_unicode_compatible
class JetSetting(SingletonModel):
    jet_admin_user = models.ForeignKey(User, verbose_name=_("Jet Dashboard Admin User"), null=True, blank=True,
                                       on_delete=models.SET_NULL)
    auto_deploy_dashboard = models.BooleanField(_("Auto deploy Dashboard to Users"), default=False)
    MENU_OPTIONS = (
        ("default", _("Default")),
        ("jet_dashboard", _("Jet Dashboard")),
        ("none", _("None"))
    )
    jet_dashboard_menu = models.CharField(_("Menu Source"), default='default', choices=MENU_OPTIONS, max_length=50)
    show_custom_menu = models.BooleanField(_("Show Custom Menu"), default=False)
    compact_menu = models.BooleanField(_("Use Compact Menu"), default=False)

    class Meta:
        verbose_name = _('Setting')
        verbose_name_plural = _('Settings')

    def __str__(self):
        return "Jet Setting"


@python_2_unicode_compatible
class JetMenuConfiguration(Sortable):
    ICONS = (
        ('icon-open-external', 'Open External'),
        ('icon-data', 'Data'),
        ('icon-settings', 'Settings'),
    )
    title = models.CharField(_("Title"), max_length=100)
    icon = models.CharField(max_length=100, choices=ICONS, blank=True, null=True)
    url = models.URLField(_("URL"), blank=True, null=True)
    app_model = models.CharField(max_length=150, null=True, blank=True)
    is_header = models.BooleanField(default=False)
    is_change_lang = models.BooleanField(default=False)
    users = models.ManyToManyField(User, verbose_name=_("Users"), blank=True)
    groups = models.ManyToManyField(Group, verbose_name=_("Groups"), blank=True)

    def __str__(self):
        output = []
        if hasattr(self, 'title_en') and self.title_en:
            output.append(self.title_en)
        if hasattr(self, 'title_ar') and self.title_ar:
            output.append(self.title_ar)
        return ' / '.join(output)

    def get_url(self):
        if self.url:
            return self.url
        if self.app_model:
            try:
                url = reverse(self.app_model)
                return url
            except:
                return None
        return None

    class Meta:
        ordering = ['order']
        verbose_name = _('Menu')
        verbose_name_plural = _('Menus')

jet/jet_dashboard/forms.py
import json
from django import forms
from django.core.exceptions import ValidationError
from jet.jet_dashboard.models import UserDashboardModule
from jet.jet_dashboard.utils import get_current_dashboard
from jet.utils import user_is_authenticated


class UpdateDashboardModulesForm(forms.Form):
    app_label = forms.CharField(required=False)
    modules = forms.CharField()
    modules_objects = []

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(UpdateDashboardModulesForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = super(UpdateDashboardModulesForm, self).clean()

        if not user_is_authenticated(self.request.user) or not self.request.user.is_staff:
            raise ValidationError('error')

        try:
            modules = json.loads(data['modules'])

            for module in modules:
                db_module = UserDashboardModule.objects.get(
                    user=self.request.user.pk,
                    app_label=data['app_label'] if data['app_label'] else None,
                    pk=module['id']
                )

                column = module['column']
                order = module['order']

                if db_module.column != column or db_module.order != order:
                    db_module.column = column
                    db_module.order = order

                    self.modules_objects.append(db_module)
        except Exception:
            raise ValidationError('error')

        return data

    def save(self):
        UserDashboardModule.objects.bulk_update(self.modules_objects,
                                                ['column', 'order'])


class AddUserDashboardModuleForm(forms.ModelForm):
    type = forms.CharField()
    module = forms.IntegerField()
    module_cls = None

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(AddUserDashboardModuleForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserDashboardModule
        fields = ['app_label']

    def clean_app_label(self):
        data = self.cleaned_data['app_label']
        return data if data != '' else None

    def clean(self):
        data = super(AddUserDashboardModuleForm, self).clean()

        if not user_is_authenticated(self.request.user) or not self.request.user.is_staff:
            raise ValidationError('error')

        if 'app_label' in data:
            index_dashboard_cls = get_current_dashboard('app_index' if data['app_label'] else 'index')
            index_dashboard = index_dashboard_cls({'request': self.request}, app_label=data['app_label'])

            if 'type' in data:
                if data['type'] == 'children':
                    module = index_dashboard.children[data['module']]
                elif data['type'] == 'available_children':
                    module = index_dashboard.available_children[data['module']]()
                else:
                    raise ValidationError('error')

                self.module_cls = module
        return data

    def save(self, commit=True):
        self.instance.title = self.module_cls.title
        self.instance.module = self.module_cls.fullname()
        self.instance.user = self.request.user.pk
        self.instance.column = 0
        self.instance.order = -1
        self.instance.settings = self.module_cls.dump_settings()
        self.instance.children = self.module_cls.dump_children()

        return super(AddUserDashboardModuleForm, self).save(commit)


class UpdateDashboardModuleCollapseForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(UpdateDashboardModuleCollapseForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserDashboardModule
        fields = ['collapsed']

    def clean(self):
        data = super(UpdateDashboardModuleCollapseForm, self).clean()

        if not user_is_authenticated(self.request.user) or not self.request.user.is_staff:
            raise ValidationError('error')

        if self.instance.user != self.request.user.pk:
            raise ValidationError('error')

        return data


class RemoveDashboardModuleForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(RemoveDashboardModuleForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserDashboardModule
        fields = []

    def clean(self):
        cleaned_data = super(RemoveDashboardModuleForm, self).clean()

        if not user_is_authenticated(self.request.user) or self.instance.user != self.request.user.pk:
            raise ValidationError('error')

        return cleaned_data

    def save(self, commit=True):
        if commit:
            self.instance.delete()


class ResetDashboardForm(forms.Form):
    app_label = forms.CharField(required=False)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(ResetDashboardForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserDashboardModule
        fields = []

    def clean(self):
        data = super(ResetDashboardForm, self).clean()
        data['app_label'] = data['app_label'] if data['app_label'] else None

        if not user_is_authenticated(self.request.user) or not self.request.user.is_staff:
            raise ValidationError('error')

        return data

    def save(self, commit=True):
        if commit:
            UserDashboardModule.objects.filter(
                user=self.request.user.pk,
                app_label=self.cleaned_data['app_label']
            ).delete()

jet/jet_dashboard/templates/jet.dashboard/dashboard.html
{% load i18n %}

<div class="dashboard-container columns_{{ columns|length }} cf">
    {% for i in columns %}
        <div class="dashboard-column-wrapper">
            <div class="dashboard-column{% if forloop.first %} first{% endif %}">
                {% for module in modules %}
                    {% if module.model.column == i %}
                        {% include "jet.dashboard/module.html" with module=module %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

<div class="dialog-confirm" id="module-remove-dialog" title="{% trans "Delete widget" %}">
    <p>{% trans "Are you sure want to delete this widget?" %}</p>
</div>

<form action="{% url "jet-dashboard:update_dashboard_modules" %}" method="POST" id="update-dashboard-modules-form">
    {% csrf_token %}
    <input type="hidden" name="app_label" value="{% if app_label %}{{ app_label }}{% endif %}">
    <input type="hidden" name="modules">
</form>

<form action="{% url "jet-dashboard:update_dashboard_module_collapse" %}" method="POST" id="update-dashboard-module-collapse-form">
    {% csrf_token %}
    <input type="hidden" name="id">
    <input type="hidden" name="collapsed">
</form>

<form action="{% url "jet-dashboard:remove_dashboard_module" %}" method="POST" id="remove-dashboard-module-form">
    {% csrf_token %}
    <input type="hidden" name="id">
</form>

jet/jet_dashboard/templates/jet.dashboard/dashboard_tools.html
{% load i18n %}

{% if request.user.jetsetting_set.exists %}
<style>
    /* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 30%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}

</style>
<div class="dashboard-tools-toggle-container">
    <a href="#" class="dashboard-tools-toggle button">
        <span class="dashboard-tools-toggle-icon icon-settings"></span>
    </a>
</div>
<div class="dashboard-tools" style="right: {% if LANGUAGE_BIDI %}20rem{% else %}33.35714rem{% endif %};">
    <div id="propagate_dashboard" href="" class="button ">{% trans 'Transfer dashboard' %}</div>
    <a id="edit_menu" href="{% url 'admin:jet_jetmenuconfiguration_changelist' %}" class="button ">{% trans 'Edit Menu' %}</a>
    <a id="clear_cache" href="{% url 'jet_dashboard:clear_cache' %}?next={{request.path}}" class="button ">{% trans 'Clear Cache' %}</a>
    <div id="generate_dashboard_apps" href="" class="button ">{% trans 'Generate Custom Dashboard' %}</div>
    <div id="manage_dashboard_config" href="" class="button ">{% trans 'Dashboard Config' %}</div>
</div>

<div class="dashboard-tools">
    <form action="{% url "jet-dashboard:add_user_dashboard_module" %}" method="POST" id="add-dashboard-module-form">
        {% csrf_token %}
        <select class="add-dashboard" name="module">
            <option>{% trans "widgets" %}</option>
            <optgroup label="{% trans "available" %}">
                {% for module in available_children %}
                    <option value="{{ forloop.counter0 }}" data-type="available_children">{{ module.title }}</option>
                {% endfor %}
            </optgroup>
            <optgroup label="{% trans "initials" %}">
                {% for module in children %}
                    <option value="{{ forloop.counter0 }}" data-type="children">{{ module.title }}</option>
                {% endfor %}
            </optgroup>
        </select><a href="#" class="button add-dashboard-link" title="{% trans "Add" %}"><span class="add-dashboard-link-icon icon-add"></span><span class="add-dashboard-link-label">{% trans "Add" %}</span></a>
        <input type="hidden" name="app_label" value="{% if app_label %}{{ app_label }}{% endif %}">
        <input type="hidden" name="type" value="">
        <a href="#" class="button transparent reset-dashboard-link" title="{% trans "Reset widgets" %}"><span class="reset-dashboard-link-icon icon-reset"></span><span class="reset-dashboard-link-label">{% trans "Reset widgets" %}</span></a>
    </form>
    <form action="{% url "jet-dashboard:reset_dashboard" %}" method="POST" id="reset-dashboard-form">
        {% csrf_token %}
        <input type="hidden" name="app_label" value="{% if app_label %}{{ app_label }}{% endif %}">
    </form>
    <div class="dialog-confirm" id="reset-dashboard-dialog" title="{% trans "Reset widgets" %}">
        <p>{% trans "Are you sure want to reset widgets?" %}</p>
    </div>
</div>

<!-- The Modal -->
<div id="confirm_action_modal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
      <form action="{% url 'jet_dashboard:propagate_jet_dashboard' %}" method="post">
          {% csrf_token %}
          <p>{% trans "Are you sure you want to fan out dashboard configuration to all staff users?..." %}</p>
        <button type="submit" class="button center" title="{% trans "Run the selected action" %}" name="index" value="{{ action_index|default:0 }}">{% trans "Yes I am sure, please apply ..." %}</button>
      </form>
  </div>
</div>
<div id="confirm_generate_custom_app" class="modal">
    <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
      <form action="{% url 'jet_dashboard:generate_custom_dashboard' %}?next={{request.path}}" method="post">
          {% csrf_token %}
          <p>{% trans "Are you sure you want to generate custom apps?..." %}</p>
        <button type="submit" class="button center" title="{% trans "Run the selected action" %}" name="index" value="{{ action_index|default:0 }}">{% trans "Yes I am sure, please apply ..." %}</button>
      </form>
  </div>
</div>
<!-- The Modal -->
<div id="manage_dashboard_config_modal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>

      <form action="{% url 'jet_dashboard:download_my_dashboard' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <br>
          <h3>{% trans 'Upload a valid configuration for for your custom Dashboard' %}</h3>
          <hr>
          <br>
          <input type="file" name="dashboard_config">
          <br><br>
          <div class="row" style="display: grid; text-align: center;">
                <button type="submit" class="button center" title="{% trans 'Upload' %}" name="index" value="{% trans 'Upload' %}">{% trans 'Upload' %}</button>
              <div class="center" style="margin: 20px;">{% trans 'OR' %}</div>
              <a class="button center" href="{% url 'jet_dashboard:download_my_dashboard' %}">{% trans 'Download Dashboard' %}</a>
          </div>
      </form>
  </div>
</div>

<script>
    // Get the modal
var modal = document.getElementById('confirm_action_modal');
var modal_gen = document.getElementById('confirm_generate_custom_app');
var modal_download = document.getElementById('manage_dashboard_config_modal');

// Get the button that opens the modal
var btn = document.getElementById("propagate_dashboard");
var btn_gen = document.getElementById("generate_dashboard_apps");
var btn_download = document.getElementById("manage_dashboard_config");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close");

// When the user clicks on the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
}
btn_gen.onclick = function() {
  modal_gen.style.display = "block";
}
btn_download.onclick = function() {
  modal_download.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
Object.keys(span).forEach(el => {
    span[el].onclick = function() {
      modal.style.display = "none";
      modal_gen.style.display = "none";
      modal_download.style.display = "none";
    }
})

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal || event.target == modal_gen || event.target == modal_download) {
    modal.style.display = "none";
    modal_gen.style.display = "none";
    modal_download.style.display = "none";
  }
}
</script>

{% endif %}

jet/jet_dashboard/templates/jet.dashboard/module.html
{% load i18n %}
{% if module.has_permission or request.user.is_superuser %}
<div class="dashboard-item{% if module.collapsible %} collapsible{% endif %}{% if module.model.collapsed %} collapsed{% endif %}{% if module.deletable %} deletable{% endif %}{% if module.ajax_load %} ajax{% endif %}{% if module.draggable %} draggable{% endif %}{% if module.children|length > 0 %} has_children{% endif %}"{% if module.ajax_load %} data-ajax-url="{% url "jet-dashboard:load_dashboard_module" pk=module.model.id %}"{% endif %} data-module-id="{{ module.model.id }}">
    <div class="dashboard-item-header {% if module.header_style == 'dark' %}dark_header{% endif %}">
        {% if module.draggable %}
            <span class="dashboard-item-header-drag icon-grid"></span>
        {% endif %}
        {% if request.user.is_superuser %}
        <span class="dashboard-item-header-buttons">
            <a href="{% url "jet-dashboard:update_module" pk=module.model.id %}" title="{% trans "Change" %}"><span class="icon-edit"></span></a>

            {% if module.deletable %}
                <a href="#" title="{% trans "Delete" %}" class="dashboard-item-remove"><span class="icon-cross"></span></a>
            {% endif %}
        </span>
        {% endif %}
        <span class="dashboard-item-header-title">
            {% if module.collapsible %}
                <a href="#" class="dashboard-item-collapse"><span class="dashboard-item-header-collapse-button icon-arrow-down"></span></a>
                <a href="#" class="dashboard-item-collapse"><span class="dashboard-item-header-collapse-button icon-arrow-up"></span></a>
            {% endif %}

            {% if module.title_url %}
                <a href="{{ module.title_url }}">{% if LANGUAGE_CODE|lower == 'ar' %}{{ module.title_ar }}{% else %}{{ module.title }}{% endif %}</a>
            {% else %}
                {% if LANGUAGE_CODE|lower == 'ar' %}{{ module.title_ar }}{% else %}{{ module.title }}{% endif %}
            {% endif %}
        </span>
        <div class="cf"></div>
    </div>

    <div class="dashboard-item-content{% if module.contrast %} contrast{% endif %}"{% if module.style %} style="{{ module.style }}"{% endif %}>
        {{ module.pre_contenta|default_if_none:"" }}
        {% if module.ajax_load %}
            <div class="loading-indicator-wrapper">
                <span class="icon-refresh loading-indicator"></span>
            </div>
        {% else %}
            {{ module.render }}
        {% endif %}
        {{ module.post_content|default_if_none:"" }}
    </div>
</div>
{% endif %}

jet/jet_dashboard/templates/jet.dashboard/update_module_fieldset.html
{% load i18n jet_tags %}

{% if wrap != False %}<fieldset class="module aligned">{% endif %}
    {% for field in form %}
        {% if field.name != 'DELETE' %}
            <div class="form-row{% if field.errors %} errors{% endif %}" {% if field.is_hidden %}style="display: None"{% endif %}>
                {{ field.errors }}

                {% if field|jet_is_checkbox %}
                    {{ field }} <label{% if field.field.required %} class="required"{% endif %} for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% else %}
                    <label{% if field.field.required %} class="required"{% endif %} for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                {% endif %}

                {% if field.field.help_text %}
                    <p class="help">{{ field.field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
{% if wrap != False %}</fieldset>{% endif %}